Repository kubevirt/cluster-api-provider-kubevirt, pull requests merged in 2021-11, with the labels that each got.

#1 Initial enablement
  .gitignore
  Dockerfile
  Makefile
  api/v1alpha4/zz_generated.deepcopy.go
  config/default/manager_image_patch.yaml
  config/manager/manager.yaml
  go.sum
  kubevirtci
Labels: size/L, approved, dco-signoff: yes, lgtm

#2 Fix sync issue on fresh capik installs
  kubevirtci
Labels: approved, size/XS, dco-signoff: yes, lgtm

#3 Adds working disk image
  kubevirtci
  templates/cluster-template.yaml
Labels: approved, dco-signoff: yes, size/S, lgtm

#6 Add a basic verification script for e2e testing
  hack/functest.sh
  kubevirtci
Labels: approved, dco-signoff: yes, lgtm, size/M

#8 Add minimal funtest make target
  Makefile
  kubevirtci
Labels: approved, size/XS, dco-signoff: yes, lgtm
